### ISSUE TITLE
The code generated from effect wont compile

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#42] opened 2015-10-19 22:07 UTC
The xtxtuml code:
```
		state finalstate {
			entry {
				if ((this->PerformanceTestModel.AB.a).isEmpty()) {
				} else {
					PerformanceTestModel.A a = (this->PerformanceTestModel.AB.a).selectAny();
					unlink(PerformanceTestModel.AB.a, a, AB.b, PerformanceTestModel.B.this);
					a.childTerminated();
				}
				delete(PerformanceTestModel.B.this);
			}
		}
```

The generated code:
```
    public class finalstate extends StateMachine.State {
      @Override
      public void entry() {
        Collection<PerformanceTestModel.A> _ralfassocnavexpression = this.assoc(PerformanceTestModel.AB.a.class);
        boolean _isEmpty = _ralfassocnavexpression.isEmpty();
        if (_isEmpty) {
        } else {
          Collection<PerformanceTestModel.A> _ralfassocnavexpression_1 = this.assoc(PerformanceTestModel.AB.a.class);
          PerformanceTestModel.A a = _ralfassocnavexpression_1.selectAny();
          Action.<PerformanceTestModel.A, PerformanceTestModel.B>unlink(PerformanceTestModel.AB.a.class, a, PerformanceTestModel.AB.b.class, B.this);
          a.childTerminated();
        }
        Action.delete(B.this);
      }
    }
```

Where this should be qualified but it isn't.

**Comment by djnemeth** [comment] 2015-10-23 08:16
This issue was caused by an unfortunate combination of missing typecheck for the navigation expression and the Java-like `this` usage. See #22 and #26.

As the type validation for custom expressions is implemented now, the problem becames an equivalent of #26, therefore I close the issue.

**Closed by djnemeth** 2015-10-23 08:16 UTC
Labels: category:XtxtUML, prio:medium, type:bug
