### ISSUE TITLE
Prefix ++ operator is not allowed but postfix is

### ISSUE THREAD

**Issue by GregoBalu** [ELTE-Soft/txtUML#348] opened 2016-05-04 14:21 UTC
![bug1](https://cloud.githubusercontent.com/assets/8973441/15016930/b9adbd96-1213-11e6-94a4-53b6ac76b8e5.png)
![bug1_a](https://cloud.githubusercontent.com/assets/8973441/15016975/f4e643c4-1213-11e6-808c-b7765797738f.png)
As seen above, while applying the prefix operator++ to an **int**, it gives an error. This is not the case when using postfix operator++. The error message is weird also, at least for me.
@nboldi can you enlighten me here?

**Comment by nboldi** [comment] 2016-05-04 14:29
I think it might be a java/xtend error message, and not our validation.

**Comment by djnemeth** [comment] 2016-05-06 09:44
Prefix operators haven't been implemented in XtxtUML yet, see [#37](https://github.com/ELTE-Soft/txtUML/issues/37#issuecomment-150489745). I believe the strange error is issued because `++count` is probably parsed as `count`, ignoring the unknown `++` token. The message is a standard Xbase one, it means that you cannot use an expressions without side effects — in this case, a variable — as a statement.

I close this as a distant duplicate of #37.

**Closed by djnemeth** 2016-05-06 09:44 UTC
Labels: type:question
