### ISSUE TITLE
Problem with CRLF

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#229] opened 2016-02-03 09:49 UTC
As mentioned in #213, a problem occurred that git showed the `Display.java` java file changing completely. Now it happened again on master with the `HandValue.java` and `ValueIfc.java` files (both in the `clock` example), and I found out that the source of the problem were indeed the line endings, as somehow these files are in the repository with `CR` `LF` instead of `LF`.

We should look further into the problem to see how this could happen.

**Comment by gerazo** [comment] 2016-02-03 10:26
Is someone overriding the settings in the repo? Can you find the change in the commit history? Who did it? :)

**Comment by gerazo** [comment] 2016-02-03 10:33
The automatic conversion is working when you commit and when you check out. But it is not working when there are mixed line endings in the file (this could be one reason). The other problem is that even if I commit back the converted version, my repository still has the wrong version. In this case, checking out the whole repository again is the good solution.

**Comment by kovacsgabor** [comment] 2016-02-03 10:46
I downloaded the whole repository in zip to see them without any automatic change, and I saw that these two files contained `CR` `LF`. (The files were created by @devaigergely81, not myself but the problem occurred in my working copy.)

I work on Windows, and I think git showed these files changed because it knows that when I push into the repository, they will automatically be converted to have `LF` instead of `CR` `LF` although all files in my working copy have `CR` `LF` line endings due to the automatic conversion.

I only added this as an issue because it happened now with three files and I thought we should look further into the matter to find the source of this problem.

**Comment by devaigergely81** [comment] 2016-02-03 10:48
Sorry, if it was me! There is a problem with example development: Examples cannot be developed in the host Eclipse, so we start a guest eclipse. But git tooling is not available in the guest, because it only offers the features of the defined target platform. So the example gets imported from the git directory into the guest eclipse by the "import existing project" wizard, and therefore git cannot kick-in with the conversions. So if the guest Eclipse uses Windows defaults for line endings, it sneaks into the repo.
Solutions:
- Set the line ending in guest eclipse. (Easy to forget.)
- Install txtuml in another Eclipse instance and use that to work on examples via git. (Time-consuming.) I'll stick to this approach.
Any suggestions?

**Comment by devaigergely81** [comment] 2016-02-03 10:59
Thinking a bit more... My above scenario with the guest Eclipse might even be even more complex: The repo is checked out in git in the host eclipse (LF to CRLF happens), example project is imported in guest eclipse. If that is configured to use LF, then mixed line endings get introduced. When git commit is done in the host eclipse, the CRLF to LF conversion may not happen for the mixed files. (?) So, is it the case that its better to use CRLF setting in the guest eclipse? Or just use the installed option (the second one in my previous note above)...

**Comment by devaigergely81** [comment] 2016-02-05 09:46
Our current solution for line end handling is a `.gitattribute` file checked in the repo. The problem is that [EGit/JGit does not support `.gitattribute` files](https://bugs.eclipse.org/bugs/show_bug.cgi?id=342372) at the moment.
I'll update the git related instructions in our internal wiki to discourage the use of EGit on Windows machines.

**Closed by devaigergely81** 2016-02-05 09:46 UTC
Labels: type:bug
