### ISSUE TITLE
Executions in a separate files lead to false errors

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#173] opened 2015-12-01 16:24 UTC
Commit 2385f9efe72ad3769e042a8ac767056fbd2f5c1e moved the executions outside the model to avoid validation errors.
When these models are freshly imported in a workspace or a clean+build happens, some of the executions are marked erroneous: The types used in them cannot be resolved. It is usually the 'train' or 'machine' example is affected.
If the file is saved after a dummy modification, the errors go away.
The problem is confirmed by @devaigergely81, @kmate, @nboldi, and it also appears if txtUML is installed.
Seems to be an Xtext/Xbase bug.

**Comment by devaigergely81** [comment] 2015-12-01 16:37
Associated exceptions:
~~~~
16089 [Worker-9] ERROR org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder  - Error initializing JvmElement
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.typesystem.references.LightweightTypeReferenceFactory.toPlainTypeReference(LightweightTypeReferenceFactory.java:117)
	at org.eclipse.xtext.xbase.typesystem.references.StandardTypeReferenceOwner.toPlainTypeReference(StandardTypeReferenceOwner.java:108)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypeReferenceBuilder.typeRef(JvmTypeReferenceBuilder.java:112)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.calculateApiSuperType(XtxtUMLJvmModelInferrer.java:788)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.access$7(XtxtUMLJvmModelInferrer.java:659)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer$18.apply(XtxtUMLJvmModelInferrer.java:554)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer$18.apply(XtxtUMLJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.initializeSafely(JvmTypesBuilder.java:206)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toClass(JvmTypesBuilder.java:384)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toClass(JvmTypesBuilder.java:361)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer._toJvmMember(XtxtUMLJvmModelInferrer.java:579)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.toJvmMember(XtxtUMLJvmModelInferrer.java:835)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.access$2(XtxtUMLJvmModelInferrer.java:819)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer$2.apply(XtxtUMLJvmModelInferrer.java:146)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer$2.apply(XtxtUMLJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.initializeSafely(JvmTypesBuilder.java:206)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toClass(JvmTypesBuilder.java:384)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toClass(JvmTypesBuilder.java:361)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer._infer(XtxtUMLJvmModelInferrer.java:151)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.infer(XtxtUMLJvmModelInferrer.java:796)
	at org.eclipse.xtext.xbase.jvmmodel.AbstractModelInferrer._infer(AbstractModelInferrer.java:51)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.infer(XtxtUMLJvmModelInferrer.java:811)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:382)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:240)
	at org.eclipse.xtext.resource.DerivedStateAwareResourceDescriptionManager.internalGetResourceDescription(DerivedStateAwareResourceDescriptionManager.java:54)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionManager$1.get(DefaultResourceDescriptionManager.java:62)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionManager$1.get(DefaultResourceDescriptionManager.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionManager.getResourceDescription(DefaultResourceDescriptionManager.java:59)
	at org.eclipse.xtext.resource.persistence.StorageAwareResourceDescriptionManager.getResourceDescription(StorageAwareResourceDescriptionManager.java:38)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.writeNewResourceDescriptions(ClusteringBuilderState.java:400)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:134)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:115)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:248)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:280)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:117)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
~~~~

**Comment by kmate** [comment] 2015-12-01 17:05
It is a type inference problem. I will check it tomorrow.

**Comment by kmate** [comment] 2015-12-02 15:23
Unfortunately I am unable to reproduce these stack traces. However, the validation errors are still present.

**Comment by kmate** [comment] 2015-12-27 15:17
I am unable to reproduce the failure with any model other than xtrain. It really could be a hidden xtext/xbase bug, but I was unable to find the root cause of the problem. Maybe @djnemeth knows xtext better and has a chance to find a solution.

**Comment by djnemeth** [comment] 2015-12-27 15:28
I'll take a look at it.

**Comment by devaigergely81** [comment] 2016-03-17 09:30
@djnemeth, what is the status of this issue?

**Comment by djnemeth** [comment] 2016-03-18 11:00
It was shelved when I started to implement ports in XtxtUML, as I hadn't been able to locate its origin until that point. I'm planning to have another take on it after the UI improvements are complete (which hopefully is just a matter of days).

**Comment by djnemeth** [comment] 2016-04-06 04:46
It turned out that this issue is not even related to *execution* language elements, it's far more general. It seems that any kind of interfile cross references (e.g. imports) *might be* affected, whose targets are XtxtUML entities containing *early-inferred* members, e.g. classes containing states. See #313 for details about the JVM inference process.

The occurrence of this bug seems to be highly indeterministic. Package and file names apparently matter. I believe concurrency play some role too. The issue is already present in earlier releases, it might be as old as XtxtUML itself.

Another interesting anomaly: suppose that we have an XtxtUML project with *problematic* package and file names. Given a problematic file — *A.xtxtuml* —, take the first XtxtUML entity which contains an early inferred member (e.g. a class with a state). Now, all cross references in other problematic XtxtUML sources — e.g. in *B.xtxtuml* —, which are referring to entities defined *after* the aforementioned element in *A.xtxtuml*, will be marked as unresolved after clean & rebuild.

It seems as if somehow the JVM inference process of an Xtext resource (e.g. an XtxtUML file) entered an invalid state after the first early-inferred member had been attached to its container. To reproduce this issue, clean & rebuild (Project > Build Automatically and then Project > Clean...) the following project: [issue173.zip](https://github.com/ELTE-Soft/txtUML/files/205758/issue173.zip). (Unused import warning are shown on the imports of Other.xtxtuml, but the phantom validation errors about unresolved references can be seen in the problems view.)

I do believe that this is related to the fact that the [JvmDeclaredTypeAcceptor](https://github.com/eclipse/xtext/blob/4e5a6842d937c9616dcf920e7b3fee9b8a6e0687/plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelAssociator.java#L495)'s [`accept`](https://github.com/eclipse/xtext/blob/4e5a6842d937c9616dcf920e7b3fee9b8a6e0687/plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelAssociator.java#L530) method — which is used in the first phase of the JVM inference process to create the skeletons of referable XtxtUML entities — actually [add](https://github.com/eclipse/xtext/blob/4e5a6842d937c9616dcf920e7b3fee9b8a6e0687/plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelAssociator.java#L532) the inferred element to the *direct* contents of the given resource. In the second phase, these skeletons might be added to the *members* of other XtxtUML entities while still being held as a direct content of the enclosing resource. I think it's worth a try to see what happens if we bypass this aspect of the default implementation.

**Closed** 2016-04-22 05:31 UTC
