### ISSUE TITLE
Change the browsing diagram window to a more convenient form

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#180] opened 2015-12-03 01:47 UTC

**Comment by dobreffandras** [comment] 2016-04-25 08:03
@kovacsgabor please specify!

**Comment by kovacsgabor** [comment] 2016-04-25 08:37
If you click on the `Browse` button, an empty window appears, without any options to choose from.

**Comment by dobreffandras** [comment] 2016-05-09 07:14
Currently the "browsing" functionality is rather a searching functionality. So if you start typing the name of your diagram it will show up. (It can be confusing that the dialog shows the recent classes)

However you're right, that the visualization does not give the best user experience. I've got plenty improvements in my mind.

**Comment by dobreffandras** [comment] 2016-10-05 12:55
A more generic version of this issue has been created: #438

**Comment by djnemeth** [comment] 2016-10-05 20:28
I close this issue as a duplicate of #438. However, providing actual browsing functionality instead of type search dialogs *might* be beneficial, so I'll mention this idea there.

**Closed by djnemeth** 2016-10-05 20:28 UTC
Labels: category:ide, prio:medium, type:bug
