### ISSUE TITLE
Certain demo diagrams cannot be visualized with JS

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#575] opened 2018-04-03 11:47 UTC
The following diagrams seem to be affected:
- `clock.x.XClockClassDiagram`
- `clock.x.XPendulumSMDiagram`
- `clock.x.XHandSMDiagram`
- `pingpong.x.XRacketSMDiagram`
- `pingpong.x.XGameSMDiagram`
- `pingpong.x.XPingPongClassDiagram`
- `pingpong.x.XPlayerSMDiagram`

Trying to visualize them with JS makes the wizard fail with an exception. No diagram is produced. Based on the type of the diagram, the following stack traces seem to appear:
- [classdiag-trace.txt](https://github.com/ELTE-Soft/txtUML/files/1871311/classdiag-trace.txt)
- [smdiag-trace.txt](https://github.com/ELTE-Soft/txtUML/files/1871312/smdiag-trace.txt)

**Comment by djnemeth** [comment] 2018-04-12 19:33
I recommend to address this in branch _[visualization-refactoring](https://github.com/ELTE-Soft/txtUML/tree/visualization-refactoring)_.

**Comment by szokolai-mate** [comment] 2018-04-13 09:55
Notice that all the diagrams with this problem use Xtxt models. So I made some testing between J and X(txt) model visualization. In all of the above examples, we can observe the following differences:

**SMDs with JointJS:** the J diagram is correct, while X is missing **all** transition triggers

**Class diagrams with JointJS:** the J diagram is correct, while X is missing **all** associations and ports 
(cannot visualize because of the missing data, so this was observed by comparing input.js files)

**SMDs with Papyrus:** cannot tell if errorous, as the transition labels are not displayed on either

**Class diagram with Papyrus:** once again, the J diagram is correct, while X is missing **all** associations and ports


All of these errors are caused by nullpointer exceptions, which are caused by missing crucial data, like the `Trigger` class in JS trying to access it's triggering events, and finding `null`.

This data is supposed to be supplied by `hu.elte.txtuml.export.uml2.mapping.ModelMapProvider.getByName(String)`, which then is supposed to return an `EObject`, which is a model object representation.

This suggests that the problem originates from the exportation, not visualization.

Upon comparing the `model.uml` and `model.notation` files it is obvious that the **supposedly eqvivalent X model's exportation is missing huge parts of the J model's.**
For example, all  connectors, associations and signals are missing form the X model's files. The notation file is also considerably shorter.

That is why I would not consider this a visualization issue, and would request reassignment.

**Comment by djnemeth** [comment] 2018-04-15 09:29
I can confirm that the UML exported from _XClock_ is more than 60% shorter than the UML exported from _Clock_. This indeed might be an issue of the UML exporter.

- @nagyandras95, could you look at the problem from the perspective of the UML exporter? I attach the exported UMLs: _[clock.j.model.uml](https://github.com/ELTE-Soft/txtUML/files/1912064/clock.j.model.uml.txt)_, _[clock.x.model.uml](https://github.com/ELTE-Soft/txtUML/files/1912066/clock.x.model.uml.txt)_. It might be relevant that `clock.x.XDisplaySMDiagram` doesn't seem to be affected.
- @szokolai-mate, could you check that the abovementioned nullpointer exceptions cannot happen in case of a successfully exported model (i.e. for any valid model JS visualization cannot fail, given the exportation is correct)?

**Closed** 2018-05-02 19:17 UTC
Labels: category:examples, category:model-export, prio:high, type:bug
